### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jairhenrique** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#17]
@b-bittner @janLo @oniboni 

The last version on pypi is [0.3.0](https://pypi.org/project/mkdocs-kroki-plugin/).
The last tag generate on this `v.0.4.0`, maybe `v.` crashed the pipe to update pypi.

Could someone generate a new release including #14

**Comment by reedsutliff** [comment]
bump

**Comment by b-bittner** [comment]
Sorry, was my mistake. fixed it with v0.5.0

**Comment by jairhenrique** [comment]
@b-bittner the version 0.5.1 has same mistake. `v.0.5.1`
