### ISSUE TITLE
414 Request-URI Too Large: Switch to POST if the URI is too long

### ISSUE THREAD

**Issue by rumbin** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#2]
## Problem Description

When an (excalidraw) drawing is too large (contains too many characters), then the URI becomes too large.
This results in the image not being renderd in MkDocs. Instead, a placeholder image is shown:

![image](https://user-images.githubusercontent.com/1220356/138250923-6e83a481-6d99-4b09-9150-874fd9726c57.png)

I _suppose_ that this is caused by the drawing code being too long.
At least that is what https://kroki.io/#try shows when providing a too long excalidraw JSON.

## Possible solution:

Switch to `POST`, either _always_ or only if the URI would become too long.
For reference, see identical issues of other languages and their solutions:

* https://github.com/yuzutech/kroki-go/issues/11
* https://github.com/Mogztter/asciidoctor-kroki/issues/42
* https://github.com/Mogztter/asciidoctor-kroki#configuration, see config param `kroki-http-method`

**Comment by oniboni** [comment]
@rumbin Can you provide some test data to reproduce the issue?

**Comment by saheljalal** [comment]
Any complicated or large export from excalidraw.com should work. Facing this as well, would be great if it could be switched to `POST`.

**Comment by b-bittner** [comment]
I just looked into this issue, but as far as I can see, there is other basic problem with that.
At the moment, default configuration is to embed the drawings in an html img tag with the URL as source.
It seems so, that Image-Tags in html can only have GET-Requests as source (Am I correct?).

If so, I only see the option to first download the drawing (which is optional at the moment).
So a solution could be:
* Small enough drawings as GET-URL inside img-tag (to maintain default settings)
* Warning/Hint when content/URL is too big (and download is disabled - as is in default)
* Always use POST-Requests when download is enabled - img-tag then uses local-img-url

Feedback please!

**Comment by saheljalal** [comment]
Not sure I fully understand the image tag reference and I have limited Python knowledge, but looking at the [plugin code](https://github.com/AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin/blob/0a613c5fc92b1e9c50d107df365fd599d40c1496/kroki/plugin.py#L119), it seems that it is using [`urlretrieve`](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlretrieve) which by default uses `GET`.

Maybe there is another way to implement this using the [standard library](https://docs.python.org/3/library/urllib.request.html) by passing in `data` and making it use `POST` instead.

**Comment by oniboni** [comment]
@b-bittner Yes, you are right. Your solution would work as a quick fix.

I looked into the asciidoc plugin and it seems, that they are doing the request via JS in the browser at a later stage. This may also be an option.

**Comment by b-bittner** [comment]
This issue should now be fixed with #7
