### ISSUE TITLE
Links to images broken when 

### ISSUE THREAD

**Issue by mat813** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#25]
I use the `DownloadImages` feature to serve static content, and my mkdocs is configured to be served from a subdirectory, not the root path, with:

```yaml
site_url: https://site.com/infra/
```

This worked just fine with 0.3.0, the replaced image definition would link to the correct place.

With 0.5.0, the generated image definition has an absolute link, and, say, `/images/kroki_generated/schemas-1cf3fe41743e0a1c1567d1e95f6f05e4.svg`, and it is is missing the `/infra` at the beginning, so the generated html does not point to the correct location.

**Comment by b-bittner** [comment]
should be fixed with #20 in the newest release v0.6.0
