### ISSUE TITLE
support whitespace after fenced block

### ISSUE THREAD

**Issue by nolange** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#34]
Hello,

I am using pandoc as reference (as "markdown formatter") and it is common that
fenced blocks contain a whitespace, like this:

~~~ markdown
``` plantuml
@startuml
stop
@enduml
```
~~~

This unfortunately does not work, but the only issue seems to be the whitespace,
this works:

~~~ markdown
```plantuml
@startuml
stop
@enduml
```
~~~

So please make the detection a bit less strict and allow whitespaces.

**Comment by oniboni** [comment]
You can achieve this via the config:
```yaml
plugins:
  ...
  - kroki:
      - FencePrefix: ' '
```

**Comment by nolange** [comment]
Nah, its not completed, I cant adjust the config for every (part of a) file. Whitespaces should not matter at all,
and dont for all other implemenations I know of.
The code has more issues, most of which are addresses in #36 , which brings it more in line with the "de jure"
spec of [fenced-code-blocks](https://spec.commonmark.org/0.31.2/#fenced-code-blocks).

**Comment by nolange** [comment]
Thanks, this project felt abandoned for a while ;)

**Comment by oniboni** [comment]
@nolange 
> Thanks, this project felt abandoned for a while ;)

I know.. We all try our best to fit this in between our normal working hours  :wink:
