### ISSUE TITLE
seems to depend on mkdocs 1.5

### ISSUE THREAD

**Issue by nolange** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#49]
The line `from mkdocs.plugins import BasePlugin as MkDocsBasePlugin, get_plugin_logger` fails with mkdocs 1.4.2,
seems to need 1.5.0 or newer: https://github.com/mkdocs/mkdocs/commit/18c01d2e74b481acb4fb516f5659a727a900b890

**Comment by b-bittner** [comment]
Thanks for your hint, just updated the dependencies.
fixed by new release 0.7.1.
