### ISSUE TITLE
Make the 'kroki-' prefix optional

### ISSUE THREAD

**Issue by kenny-chow-my** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#5]
We have our Markdown rendered in 2 places: Gitlab Markdown preview and custom mkdocs website. 
Gitlab's implementation of diagrams in Markdown does not require the `kroki-` prefix. https://docs.gitlab.com/ee/administration/integration/kroki.html

Example: 
```
    ```plantuml
    Bob -> Alice : hello
    Alice -> Bob : hi
    ```
```

To make the sites compatible, we would like to remove the `kroki-` prefix in the code block `kroki-plantuml`.

**Comment by kenny-chow-my** [comment]
This PR seems to enable the functionality: https://github.com/AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin/pull/4/files

**Comment by b-bittner** [comment]
Thanks for your request, somehow @oniboni  was already implementing this (also bis Thanks!).
So. PR #4  is submitted, so this issue can be closed.
