### ISSUE TITLE
Allow ServerURL to be set through environment variables

### ISSUE THREAD

**Issue by zhammer** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#50]
We use mkdocs-kroki-plugin to render [techdocs](https://backstage.io/docs/features/techdocs/how-to-guides/#how-to-add-mermaid-support-in-techdocs) in our organization's Backstage.

We want to enforce ServerURL while building our docs in the techdocs builder, rather than having users set the ServerURL in their `kroki:` config.

1. We don't want to risk a user forgetting to set this and sending diagrams to kroki.io
2. We'd like to set different ServerURL per environment

**Comment by oniboni** [comment]
Alternatively you can also [use environment variables via mkdocs config](https://www.mkdocs.org/user-guide/configuration/#environment-variables):
```yaml
  - kroki:
      ServerURL: !ENV KROKI_SERVER_URL
```
