### ISSUE TITLE
Image does not render when inside HTML tags

### ISSUE THREAD

**Issue by vaceal** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#61]
Hello,

The following markdown file does not render kroki-mermaid diagram when inside the html tag, instead it displays the markdown image tag:

```html
<details>
    <summary><u>Show Sequence diagram...</u></summary>
``kroki-mermaid
graph TD
    a --> b
``
</details>

``kroki-mermaid
graph TD
    a --> b
``
```

![image](https://github.com/AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin/assets/6855722/1de5cced-f01c-47c9-97cd-d524fc6d4a14)

Should this be supported by the plugin?

**Comment by oniboni** [comment]
I would love to see this working too!

Sadly the markdown inside of html gets not reevaluated by mkdocs as we were expecting.
I've added a small quick and dirty fix, to prove this point.

#37 should be the way to go though.
