### ISSUE TITLE
Bug: 400 Syntax error using @from-file plantuml diagrams

### ISSUE THREAD

**Issue by sblausten** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#68]
Using the latest release version 0.8.0 when I try to render a platuml diagram using the @from-file directive I get the following:

<img width="511" alt="Screenshot 2024-06-19 at 13 08 59" src="https://github.com/AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin/assets/7934833/2f5a9367-94ec-4bf8-85a8-e37d781356a7">

<img width="539" alt="Screenshot 2024-06-19 at 13 09 42" src="https://github.com/AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin/assets/7934833/b4ed0694-0c1b-4fac-94f6-692d7126c563">

```markdown
kroki-plantuml
\```kroki-plantuml
@from-file:assets/diagram.plantuml
\```
```

and the file contents is just an example diagram:
```
@startuml
Bob -> Alice : hello
@enduml
```

Has anyone else seen this behaviour?

**Comment by oniboni** [comment]
I can reproduce the error. Seems the file data is not read in correctly.

**Comment by oniboni** [comment]
I'm closing this one, bc it is not a but but a typo in the given example.

Feel free to open a new issue, if there are other problems.
