### ISSUE TITLE
Release 0.8.1 to pypi 

### ISSUE THREAD

**Issue by sblausten** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#69]
The latest patch version does not seem to be available on https://pypi.org/project/mkdocs-kroki-plugin/#history

It looks like the workflow to publish it was run successfully https://github.com/AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin/actions/runs/9330108017

**Comment by oniboni** [comment]
Yes you are right, thank you for the heads up!

Fixed.
